name: Bookstagram
description: A new Flutter project.

publish_to: 'none'
version: 1.0.2+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  google_fonts:
  provider: 
  firebase_auth:
  firebase_storage:
  firebase_analytics:
  firebase_messaging:
  google_sign_in:
  cloud_firestore:
  flutter_spinkit: 
  image_picker:
  cupertino_icons: ^0.1.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/logos/
